### ISSUE TITLE
windows利用失败

### ISSUE THREAD

**Issue by TryA9ain** [0671/RabR#1]
![image](https://user-images.githubusercontent.com/51145610/125029890-dfe91500-e0bc-11eb-8fff-73663104ffc2.png)

**Comment by 0671** [comment]
在Redis 4.0以上才支持模块导入的功能，你这个是3版本，所以在攻击中无法利用，工具支持对低版本的Windows下的Redis进行dll劫持，工具中也有对应的提示：[√] Can use master-slave replication to hijack dbghelp.dll to attack the redis

**Comment by TryA9ain** [comment]
> 在Redis 4.0以上才支持模块导入的功能，你这个是3版本，所以在攻击中无法利用，工具支持对低版本的Windows下的Redis进行dll劫持，工具中也有对应的提示：[√] Can use master-slave replication to hijack dbghelp.dll to attack the redis

ok，已知晓和成功使用，谢谢师傅的解答
