### ISSUE TITLE
Brownie+cs上线即掉线怎么解

### ISSUE THREAD

**Issue by go-bi** [0671/RabR#3]
没使用默认的dbghelp.dll，采用Brownie默认替换cs测试redis 3.0.504 上线后cs就自动掉线了

**Comment by 0671** [comment]
这个感觉像是被杀了

**Comment by go-bi** [comment]
本地win10测试全部关闭的自带的杀毒，也是上线就自动掉线。只有在重启redis服务后才能持续上线。

**Comment by 0671** [comment]
> 2、为了避免只能劫持1次dll，在dllmain.cpp的 Hijack();后增加 FreeLibrary(hModule);    
 试下加下FreeLibrary
